//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAnalisis2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Analigrupo5Entities : DbContext
    {
        public Analigrupo5Entities()
            : base("name=Analigrupo5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Clientes> T_Clientes { get; set; }
        public virtual DbSet<T_color> T_color { get; set; }
        public virtual DbSet<T_Detalle> T_Detalle { get; set; }
        public virtual DbSet<T_Empleados> T_Empleados { get; set; }
        public virtual DbSet<T_Factura> T_Factura { get; set; }
        public virtual DbSet<T_Motorista> T_Motorista { get; set; }
        public virtual DbSet<T_Nivel> T_Nivel { get; set; }
        public virtual DbSet<T_Producto> T_Producto { get; set; }
        public virtual DbSet<T_Proveedor> T_Proveedor { get; set; }
        public virtual DbSet<T_Tipo> T_Tipo { get; set; }
        public virtual DbSet<T_Usuarios> T_Usuarios { get; set; }
    }
}
