//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAnalisis2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Detalle
    {
        public int Id_Detalle { get; set; }
        public Nullable<int> Id_Factura { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Precio { get; set; }
    
        public virtual T_Factura T_Factura { get; set; }
        public virtual T_Producto T_Producto { get; set; }
    }
}
