//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAnalisis2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Factura()
        {
            this.T_Detalle = new HashSet<T_Detalle>();
        }
    
        public int Id_Factura { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual T_Clientes T_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Detalle> T_Detalle { get; set; }
        public virtual T_Empleados T_Empleados { get; set; }
    }
}
