//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAnalisis2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuarios
    {
        public int Id_usuario { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Nivel { get; set; }
        public string Usuario { get; set; }
        public string Passw { get; set; }
    
        public virtual T_Empleados T_Empleados { get; set; }
        public virtual T_Nivel T_Nivel { get; set; }
    }
}
